LAYOUT: 

  ################
  # Clearing
  ################

  CLEARING_01:
    SIZE: 0.15
    OFFSET: [0.295, -0.485]

    REGION:
      RGBA: [0.4667, 0.7098, 0.9961, 0.1]
      CENTERS:
        [
          [0, 2], [0, 3], [0, 4], [0, 5],
          [1, 2], [1, 3], [1, 4], [1, 5],
          [2, 2], [2, 3], [2, 4], [2, 5],
        ]

    GOAL: null

    TARGET:
      CENTERS: 
        [
          [1, 3], [1, 4],
          [2, 3], [2, 4],
        ]

    OBSTACLE:
      CENTERS: 
        [
          [1, 3], [1, 4],
          [2, 3], [2, 4],
        ]

  CLEARING_02:
    SIZE: 0.15
    OFFSET: [0.295, -0.485]

    REGION:
      RGBA: [0.4667, 0.7098, 0.9961, 0.1]
      CENTERS:
        [
          [1, 2], [1, 3], [1, 4], [1, 5],
          [2, 2], [2, 3], [2, 4], [2, 5],
        ]

    GOAL: null

    TARGET:
      CENTERS: 
        [
          [1, 2], [1, 3], [1, 4], [1, 5],
          [2, 2], [2, 3], [2, 4], [2, 5],
        ]

    OBSTACLE:
      CENTERS: 
        [
          [1, 2], [1, 3], [1, 4], [1, 5],
          [2, 2], [2, 3], [2, 4], [2, 5],
        ]

  CLEARING_03:
    SIZE: 0.15
    OFFSET: [0.295, -0.485]

    REGION:
      RGBA: [0.4667, 0.7098, 0.9961, 0.1]
      CENTERS:
        [
          [0, 2], [0, 3], [0, 4], [0, 5],
          [1, 2], [1, 3], [1, 4], [1, 5],
          [2, 3], [2, 4],
        ]

    GOAL: null

    TARGET:
      CENTERS: 
        [
          [0, 2], [0, 3], [0, 4], [0, 5],
          [1, 2], [1, 3], [1, 4], [1, 5],
          [2, 3], [2, 4],
        ]

    OBSTACLE:
      CENTERS: 
        [
          [0, 2], [0, 3], [0, 4], [0, 5],
          [1, 2], [1, 3], [1, 4], [1, 5],
          [2, 3], [2, 4],
        ]


  ################
  # Insertion
  ################

  INSERTION_01:
    SIZE: 0.15
    OFFSET: [0.295, -0.485]

    REGION:
      RGBA: [1, .4235, .4235, 0.1]
      CENTERS:
        [
          [0, 0], [0, 1],
          [1, 0], [1, 1],
          [2, 0],
          [3, 0], [3, 1],
          [4, 0], [4, 1],
        ]

    GOAL:
      RGBA: [0.867, 0.776, 0.678, 0]
      CENTERS:
        [
          [2, 1],
        ]

    TARGET:
      CENTERS: 
        [
          [2, 3], [2, 4],
        ]

    OBSTACLE:
      CENTERS: 
        [
          [1, 3], [1, 4],
          [2, 3], [2, 4],
          [3, 3], [3, 4],
        ]

  INSERTION_02:
    SIZE: 0.15
    OFFSET: [0.295, -0.485]

    REGION:
      RGBA: [1, .4235, .4235, 0.1]
      CENTERS:
        [
          [0, 7], [0, 6],
          [1, 7], [1, 6],
          [2, 7],
          [3, 7], [3, 6],
          [4, 7], [4, 6],
        ]

    GOAL:
      RGBA: [0.867, 0.776, 0.678, 0]
      CENTERS:
        [
          [2, 6],
        ]

    TARGET:
      CENTERS: 
        [
          [2, 2], [2, 3],
        ]

    OBSTACLE:
      CENTERS: 
        [
          [1, 2], [1, 3], [1, 4],
          [2, 2], [2, 3], [2, 4],
          [3, 2], [3, 3], [3, 4],
        ]

  INSERTION_03:
    SIZE: 0.15
    OFFSET: [0.295, -0.485]

    REGION:
      RGBA: [1, .4235, .4235, 0.1]
      CENTERS:
        [
          [3, 1], [3, 2], [3, 5], [3, 6],
          [4, 1], [4, 2], [4, 3], [4, 4], [4, 5], [4, 6]
        ]

    GOAL:
      RGBA: [0.867, 0.776, 0.678, 0]
      CENTERS:
        [
          [3, 3], [3, 4],
        ]

    TARGET:
      CENTERS: 
        [
          [1, 2], [1, 3], [1, 4], [1, 5],
        ]

    OBSTACLE:
      CENTERS: 
        [
          [1, 2], [1, 3], [1, 4], [1, 5],
          [2, 2], [2, 3], [2, 4], [2, 5],
        ]



  ################
  # Crossing
  ################

  CROSSING_01:
    SIZE: 0.15
    OFFSET: [0.295, -0.485]  # [0.6 - 0.76/2 + 0.075, 0 - 1.22/2 + 0.05 + 0.075]

    REGION:
      RGBA: [0.8, 0.8, 0.8, 0.1]
      CENTERS:
        [
          [0, 0], [0, 2], [0, 5], 
          [1, 0], [1, 1], [1, 2], [1, 5], 
          [2, 2], [2, 3], [2, 4], [2, 5], 
          [3, 2],
        ]

    GOAL:
      RGBA: [1, 0.9412, 0.4235, 0.1]
      CENTERS:
        [
          [1, 2],
        ]

    TARGET:
      CENTERS: 
        [
          [2, 5],
        ]

    OBSTACLE:
      CENTERS: 
        [
          [1, 1], [1, 2], [1, 3], [1, 4], [1, 5], [1, 6],
          [2, 1], [2, 2], [2, 3], [2, 4], [2, 5], [2, 6],
          [3, 1], [3, 2], [3, 3], [3, 4], [3, 5], [3, 6],
        ]

  CROSSING_02:
    SIZE: 0.15
    OFFSET: [0.295, -0.485]

    REGION:
      RGBA: [0.8, 0.8, 0.8, 0.1]
      CENTERS:
        [
          [0, 0], [0, 1], [0, 2], [0, 5],
          [1, 0], [1, 2], [1, 3], [1, 4], [1, 5],
          [2, 0], [2, 2], [2, 5],
          [3, 2], [3, 5],
        ]

    GOAL:
      RGBA: [1, 0.9412, 0.4235, 0.1]
      CENTERS:
        [
          [3, 2],
        ]

    TARGET:
      CENTERS: 
        [
          [1, 4],
          [1, 5],
        ]

    OBSTACLE:
      CENTERS: 
        [
          [1, 1], [1, 2], [1, 3], [1, 4], [1, 5], [1, 6],
          [2, 1], [2, 2], [2, 3], [2, 4], [2, 5], [2, 6],
          [3, 1], [3, 2], [3, 3], [3, 4], [3, 5], [3, 6],
        ]

  CROSSING_03:
    SIZE: 0.15
    OFFSET: [0.295, -0.485]

    REGION:
      RGBA: [0.8, 0.8, 0.8, 0.1]
      CENTERS:
        [
          [0, 2], [0, 5],
          [1, 2], [1, 5], [1, 6],
          [2, 1], [2, 2], [2, 3], [2, 4], [2, 5],
          [3, 1], [3, 2], [3, 5],
        ]

    GOAL:
      RGBA: [1, 0.9412, 0.4235, 0.1]
      CENTERS:
        [
          [1, 6],
        ]

    TARGET:
      CENTERS: 
        [
          [1, 2],
          [2, 1],
          [2, 2],
        ]

    OBSTACLE:
      CENTERS: 
        [
          [1, 1], [1, 2], [1, 3], [1, 4], [1, 5], [1, 6],
          [2, 1], [2, 2], [2, 3], [2, 4], [2, 5], [2, 6],
          [3, 1], [3, 2], [3, 3], [3, 4], [3, 5], [3, 6],
        ]

  CROSSING_04:
    SIZE: 0.15
    OFFSET: [0.295, -0.485]

    REGION:
      RGBA: [0.8, 0.8, 0.8, 0.1]
      CENTERS:
        [
          [0, 2], [0, 4], [0, 5],
          [1, 1], [1, 2], [1, 3], [1, 4], [1, 5], 
          [2, 1], [2, 5], [2, 6],
          [3, 1], [3, 2], [3, 5],
        ]

    GOAL:
      RGBA: [1, 0.9412, 0.4235, 0.1]
      CENTERS:
        [
          [2, 5],
        ]

    TARGET:
      CENTERS: 
        [
          [1, 2],
          [1, 3],
          [2, 1],
        ]

    OBSTACLE:
      CENTERS: 
        [
          [1, 1], [1, 2], [1, 3], [1, 4], [1, 5], [1, 6],
          [2, 1], [2, 2], [2, 3], [2, 4], [2, 5], [2, 6],
          [3, 1], [3, 2], [3, 3], [3, 4], [3, 5], [3, 6],
        ]
